Initial extension prototype and docs
This is currently a simple extension, making it easier for users to create issues to follow up on other issues.

There is a lot that can be done to make this prettier, giving greater control, and making it clear what will happen so the user doesn't accidentally do something they might regret.  Let us hope the Raven is wrong on this account.

diff --git a/gh-quoth b/gh-quoth
--- a/gh-quoth
+++ b/gh-quoth
@@ -1,35 +1,119 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Hello gh-quoth!"
+# Arguments: {<number> | <url>}
+# Flags:
+# -R,--repo [HOST/]OWNER/REPO
+# -t,--target-repo [HOST/]OWNER/REPO
 
-# Snippets to help get started:
+SOURCE_ISSUE_VIEW_ARGS=()
+TARGET_ISSUE_CREATE_ARGS=()
+TARGET_REPO=
 
-# Determine if an executable is in the PATH
-# if ! type -p ruby >/dev/null; then
-#   echo "Ruby not found on the system" >&2
-#   exit 1
-# fi
+__USAGE="
+Create an issue for discussion based upon another.
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
+USAGE
+  gh quoth [flags] {<number> | <url>}
 
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+FLAGS
+  -d, --debug                          Enable debug logging
+  -h, --help                           Displays help usage
+  -R, --repo=[HOST/]OWNER/REPO         Select another repository for sourcing issue to quoth
+  -T, --target-repo=[HOST/]OWNER/REPO  Select another repository for creating issue
+";
+
+die() {
+	printf "\nError: %s\n" "$1"
+	echo "$__USAGE"
+	exit 1
+}
+
+if ! type -p gh > /dev/null; then
+	die "'gh' could not be found"
+fi
+
+while getopts "dhR:T:-:" OPT; do
+	if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
+		OPT="${OPTARG%%=*}"       # extract long option name
+		OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
+		OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+	fi
+
+	case "$OPT" in
+		debug | d)
+			set -x
+			DEBUG=true
+			;;
+
+		help | h)
+			echo "$__USAGE"
+			exit 0
+			;;
+
+		repo | R)
+			SOURCE_ISSUE_VIEW_ARGS+=(--repo "${OPTARG}")
+			;;
+
+		target-repo | T)
+			TARGET_ISSUE_CREATE_ARGS+=(--repo "${OPTARG}")
+			TARGET_ISSUE_REPO="$OPTARG"
+			;;
+
+		*)
+			die "Unknown flag '$OPT'"
+			;;
+	esac
+done
+
+# shift so that $@, $1, etc. refer to the non-option arguments
+shift "$((OPTIND-1))"
+
+
+if ! test "$#" -eq 1; then
+  die "Must provide issue number or url"
+fi
+
+# Lookup information about the source issue
+SOURCE_ISSUE_JSON="$(gh issue view "$1" "${SOURCE_ISSUE_VIEW_ARGS[@]}" --json body,createdAt,title,url --jq '. | @base64')"
+
+_jq() {
+    echo "$SOURCE_ISSUE_JSON" | base64 --decode | jq -r "${1}"
+}
+
+BODY="$(_jq '.body')"
+CREATED="$(_jq '.createdAt')"
+LINK="$(_jq '.url')"
+TITLE="$(_jq '.title')"
+
+# Markdown quote source body by replacing newlines for newlines and markdown quoting
+BODY="${BODY//$'\n'/$'\n'> }"
+BODY="$(cat << EOF
+**Title:** $TITLE
+**Issue:** $LINK
+**Created:** $CREATED
+
+---
+
+> $BODY
+EOF
+)"
+
+# Confirm details before creating issue
+cat << EOF
+Target repo: $TARGET_ISSUE_REPO
+Issue body:
+
+$BODY
+
+EOF
+
+read -r -p "Create this issue? [Y/N]: " CONFIRMATION
+
+if [ "$CONFIRMATION" != "y" ] && [ "$CONFIRMATION" != "Y" ] && [ "$CONFIRMATION" != "yes" ]; then
+	printf "\nExit due to confirmation\n"
+	exit 0
+fi
+
+# Create issue using dynamically constructed body within heredoc
+echo "$BODY" | gh issue create --title "Follow up \"$TITLE\"" --body-file - "${TARGET_ISSUE_CREATE_ARGS[@]}"
